# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    runs-on: [ self-hosted, nixos, vod2pod ]

    steps:
    - uses: actions/checkout@v6

    - name: Build
      run: nix build .#vod2pod-rss

    - name: Test
      run: nix flake check