name: stable image
on:
  push:
    branches: [ stable ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency: ${{ github.head_ref || github.ref_name }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  cargo_version_bump:
    permissions:
      contents: write
    runs-on: [ self-hosted, nixos, vod2pod ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump patch version
        run: |
          VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
          NEW_VERSION=$(echo $VERSION | awk -F "." '{print $1"."$2"."($3+1)}')
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          sed -i "s/^version = \"$VERSION\"/version = \"$NEW_VERSION\"/" Cargo.toml
        shell: bash
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v$VERSION -m "version $VERSION"
          git commit -a -m "Bump patch version to $NEW_VERSION"
          git pull --rebase origin stable
          git push origin HEAD --follow-tags
          git fetch --unshallow || true
          git checkout main
          git merge stable
          git push origin HEAD --follow-tags
          git checkout stable

  push_to_ghcr_amd64:
      needs: cargo_version_bump
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh stable
          shell: bash
        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | buildah login --username "${{ github.actor }}" --password-stdin ghcr.io
          shell: bash
        - name: Build and push
          run: |
            buildah build \
              --platform linux/amd64 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64 \
              -f Dockerfile .
            buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64
          shell: bash
  push_to_ghcr_arm64:
      needs: cargo_version_bump
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh stable
          shell: bash
        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | buildah login --username "${{ github.actor }}" --password-stdin ghcr.io
          shell: bash
        - name: Build and push
          run: |
            buildah build \
              --platform linux/arm64 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64 \
              -f Dockerfile .
            buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64
          shell: bash
  push_to_ghcr_arm_v7:
      needs: cargo_version_bump
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh stable
          shell: bash
        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | buildah login --username "${{ github.actor }}" --password-stdin ghcr.io
          shell: bash
        - name: Build and push
          run: |
            buildah build \
              --platform linux/arm/v7 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7 \
              -f Dockerfile .
            buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7
          shell: bash
  merge_tags:
      needs: [push_to_ghcr_arm64, push_to_ghcr_arm_v7, push_to_ghcr_amd64]
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | buildah login --username "${{ github.actor }}" --password-stdin ghcr.io
          shell: bash
        - name: Create manifest for latest
          run: |
            buildah manifest create vod2pod-rss:latest
            buildah manifest add vod2pod-rss:latest ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64
            buildah manifest add vod2pod-rss:latest ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64
            buildah manifest add vod2pod-rss:latest ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7
            buildah manifest push --all vod2pod-rss:latest ghcr.io/${{ github.repository_owner }}/vod2pod-rss:latest
          shell: bash
        - name: Create manifest for version
          run: |
            buildah manifest create vod2pod-rss:${{ env.VERSION }}
            buildah manifest add vod2pod-rss:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64
            buildah manifest add vod2pod-rss:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64
            buildah manifest add vod2pod-rss:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7
            buildah manifest push --all vod2pod-rss:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}
          shell: bash
