name: beta image
on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency: ${{ github.head_ref || github.ref_name }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  push_to_ghcr_amd64:
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Login to GHCR
          run: sudo buildah login --username "${{ github.actor }}" --password-stdin ghcr.io <<< "${{ secrets.GITHUB_TOKEN }}"
          shell: bash
        - name: Build and push
          run: |
            sudo buildah build \
              --platform linux/amd64 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta \
              -f Dockerfile .
            sudo buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta
          shell: bash
  push_to_ghcr_arm64:
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Login to GHCR
          run: sudo buildah login --username "${{ github.actor }}" --password-stdin ghcr.io <<< "${{ secrets.GITHUB_TOKEN }}"
          shell: bash
        - name: Build and push
          run: |
            sudo buildah build \
              --platform linux/arm64 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta \
              -f Dockerfile .
            sudo buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta
          shell: bash
  push_to_ghcr_arm_v7:
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Login to GHCR
          run: sudo buildah login --username "${{ github.actor }}" --password-stdin ghcr.io <<< "${{ secrets.GITHUB_TOKEN }}"
          shell: bash
        - name: Build and push
          run: |
            sudo buildah build \
              --platform linux/arm/v7 \
              -t ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta \
              -f Dockerfile .
            sudo buildah push ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta
          shell: bash
  merge_tags:
      needs: [push_to_ghcr_arm64, push_to_ghcr_arm_v7, push_to_ghcr_amd64]
      permissions:
        contents: read
        packages: write
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Login to GHCR
          run: sudo buildah login --username "${{ github.actor }}" --password-stdin ghcr.io <<< "${{ secrets.GITHUB_TOKEN }}"
          shell: bash
        - name: Create manifest for beta
          run: |
            sudo buildah manifest create vod2pod-rss:beta
            sudo buildah manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta
            sudo buildah manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta
            sudo buildah manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta
            sudo buildah manifest push --all vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:beta
          shell: bash
        - name: Create manifest for version-beta
          run: |
            sudo buildah manifest create vod2pod-rss:${{ env.VERSION }}-beta
            sudo buildah manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta
            sudo buildah manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta
            sudo buildah manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta
            sudo buildah manifest push --all vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-beta
          shell: bash
