name: beta image
on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

concurrency: ${{ github.head_ref || github.ref_name }}

jobs:
  push_to_ghcr_amd64:
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            # Get the current version
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: |
            sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Build with Buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-amd64-beta
            context: ./
            dockerfiles: ./Dockerfile
            platforms: linux/amd64
            build-args: |
              BUILDKIT_INLINE_CACHE=1
            cache-from: type=gha,scope=main-amd64
            cache-to: type=gha,mode=max,scope=main-amd64
        - name: Push to GHCR
          uses: redhat-actions/push-to-registry@v2.7.1
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-amd64-beta
            registry: ghcr.io/${{ github.repository_owner }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  push_to_ghcr_arm64:
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: Bump patch version
          run: |
            # Get the current version
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: |
            sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Build with Buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-arm64-beta
            context: ./
            dockerfiles: ./Dockerfile
            platforms: linux/arm64
            build-args: |
              BUILDKIT_INLINE_CACHE=1
            cache-from: type=gha,scope=main-arm64
            cache-to: type=gha,mode=max,scope=main-arm64
        - name: Push to GHCR
          uses: redhat-actions/push-to-registry@v2.7.1
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-arm64-beta
            registry: ghcr.io/${{ github.repository_owner }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  push_to_ghcr_arm_v7:
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: Set Swap Space
          uses: pierotofy/set-swap-space@v1.0
          with:
            swap-size-gb: 10
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            # Get the current version
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: remove dev deps and version (for cache purposes)
          run: |
            sh .github/workflows/remove_dev_deps_and_version.sh beta
          shell: bash
        - name: Build with Buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-armv7-beta
            context: ./
            dockerfiles: ./Dockerfile
            platforms: linux/arm/v7
            build-args: |
              BUILDKIT_INLINE_CACHE=1
              CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            cache-from: type=gha,scope=main-armv7
            cache-to: type=gha,mode=max,scope=main-armv7
        - name: Push to GHCR
          uses: redhat-actions/push-to-registry@v2.7.1
          with:
            image: vod2pod-rss
            tags: ${{ env.VERSION }}-armv7-beta
            registry: ghcr.io/${{ github.repository_owner }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  merge_tags:
      needs: [push_to_ghcr_arm64, push_to_ghcr_arm_v7, push_to_ghcr_amd64]
      runs-on: [ self-hosted, nixos, vod2pod ]
      steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: get version
          run: |
            # Get the current version
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Login to GHCR with Podman
          uses: redhat-actions/podman-login@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Create manifest for beta
          run: |
            podman manifest create vod2pod-rss:beta
            podman manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta
            podman manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta
            podman manifest add vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta
            podman manifest push vod2pod-rss:beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:beta
        - name: Create manifest for version-beta
          run: |
            podman manifest create vod2pod-rss:${{ env.VERSION }}-beta
            podman manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-amd64-beta
            podman manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-arm64-beta
            podman manifest add vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-armv7-beta
            podman manifest push vod2pod-rss:${{ env.VERSION }}-beta ghcr.io/${{ github.repository_owner }}/vod2pod-rss:${{ env.VERSION }}-beta
